// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt2JpEZckOz5n-N6ZQLFy5soPd2hiVTvo',
    appId: '1:152569932828:web:6b1d20a0626717ef6503d9',
    messagingSenderId: '152569932828',
    projectId: 'joygo-chiayi',
    authDomain: 'joygo-chiayi.firebaseapp.com',
    storageBucket: 'joygo-chiayi.firebasestorage.app',
    measurementId: 'G-SZ10QTQWXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM9pwEYM7L-FPDYRD-ubA2lGzuEHWsjs4',
    appId: '1:152569932828:android:5e5ad147c149953f6503d9',
    messagingSenderId: '152569932828',
    projectId: 'joygo-chiayi',
    storageBucket: 'joygo-chiayi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-YXuPIkhX2pX0VRKckO9UVUtFFLoSIUg',
    appId: '1:152569932828:ios:c420139a3bd9ad396503d9',
    messagingSenderId: '152569932828',
    projectId: 'joygo-chiayi',
    storageBucket: 'joygo-chiayi.firebasestorage.app',
    iosBundleId: 'com.example.chiayicityClaudep1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-YXuPIkhX2pX0VRKckO9UVUtFFLoSIUg',
    appId: '1:152569932828:ios:c420139a3bd9ad396503d9',
    messagingSenderId: '152569932828',
    projectId: 'joygo-chiayi',
    storageBucket: 'joygo-chiayi.firebasestorage.app',
    iosBundleId: 'com.example.chiayicityClaudep1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt2JpEZckOz5n-N6ZQLFy5soPd2hiVTvo',
    appId: '1:152569932828:web:43878fea116ff2e26503d9',
    messagingSenderId: '152569932828',
    projectId: 'joygo-chiayi',
    authDomain: 'joygo-chiayi.firebaseapp.com',
    storageBucket: 'joygo-chiayi.firebasestorage.app',
    measurementId: 'G-BQZVCJDNWX',
  );
}
